// src/components/react/Counter.tsx
import  { CSSProperties, useState } from 'react'

const style: CSSProperties = {
  border: '1px solid green',
  padding: '5px',
  margin: '5px'
}

export default function Counter({
  initialCount = 0, 
  step = 1
}) {
  const [count, setCount] = useState(initialCount)
  const increment = () => setCount(c => c + step)
  return (
    <div style={style}>
      <button onClick={increment}>count:{count}</button>
    </div>
  )
}

// A trick that could write less type annotation.

// src/components/Vue/Counter.vue
<script setup lang="ts">
import { ref } from 'vue'

const count = ref(0)
</script>

<template>
  <div class="vue-component">
    <h3>From Vue.js!</h3>
    <p>count: {{ count }}</p>
    <button @click="count++">
      increment
    </button>
  </div>
</template>

<style lang="postcss" scoped>
.vue-component {
    padding: 5px;
    margin: 5px;
    border: 1px solid palevioletred;
}
</style>
